tor:
  host: localhost
  socksPort: 9050
  httpPort: 8118
  controlPort: 9051
  password: '""'

db:
  url: jdbc:postgresql://localhost:5433/scraperdb
  username: scraper
  password: Scraper_db!

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR