spark:
  database:
    jdbcUrl: jdbc:postgresql://localhost:5433/scraperdb
    props:
      user: scraper
      password: Scraper_db!
      driver: org.postgresql.Driver
      fetchsize: 1000

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
